export type BlogPostStatus = 'draft' | 'published'

export type BlogPost = {
  audience: string
  author: string
  body: string[]
  clusterSlug: string
  ctaType: 'artist-alpha' | 'fan-alpha' | 'learn-more'
  excerpt: string
  featuredImage: string
  funnelStage: 'awareness' | 'consideration' | 'conversion'
  isPillar?: boolean
  metaDescription: string
  metaTitle: string
  primaryKeyword: string
  publishedAt: string
  readingTime: string
  searchIntent: string
  secondaryKeywords: string[]
  slug: string
  status: BlogPostStatus
  title: string
  updatedAt: string
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'free-music-distribution-for-independent-artists',
    title: 'Free Music Distribution for Independent Artists',
    metaTitle: 'Free Music Distribution for Independent Artists | FanFactors',
    metaDescription:
      'Learn what free music distribution means, where it helps artists, and why ownership still matters after release day.',
    excerpt:
      'Free distribution can help music reach stores, but artists still need a plan for ownership, pricing, and fan demand.',
    clusterSlug: 'free-music-distribution',
    primaryKeyword: 'free music distribution',
    secondaryKeywords: ['free music distributor', 'release music for free', 'independent artist distribution'],
    audience: 'Independent artists',
    searchIntent: 'Learn how free music distribution works before choosing a release strategy.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/artist-rebel-vocalist.webp',
    ctaType: 'artist-alpha',
    status: 'published',
    isPillar: true,
    body: [
      'Free music distribution can be useful when the goal is reach. It helps artists put songs into the places listeners already use.',
      'The harder question is what happens after the release. FanFactors is built around the idea that artists should keep building value after distribution by giving fans a legal way to support, buy, and share artist-approved music.',
    ],
  },
  {
    slug: 'how-to-release-music-without-losing-control',
    title: 'How to Release Music Without Losing Control',
    metaTitle: 'How to Release Music Without Losing Control | FanFactors',
    metaDescription:
      'A practical release checklist for artists who want reach without giving up control of rights, pricing, and fan relationships.',
    excerpt: 'Releasing music is not just uploading a file. It is deciding how rights, demand, and fan attention will work.',
    clusterSlug: 'free-music-distribution',
    primaryKeyword: 'release music independently',
    secondaryKeywords: ['music release checklist', 'artist ownership', 'independent music release'],
    audience: 'Independent artists',
    searchIntent: 'Find a release strategy that protects artist control.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-rap-vocalist.jpg',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'A controlled release starts with clean metadata, clear rights, and a plan for what fans should do next.',
      'FanFactors adds a marketplace layer to that plan by giving artist-approved music a place where demand can be organized legally.',
    ],
  },
  {
    slug: 'free-vs-paid-music-distribution',
    title: 'Free vs Paid Music Distribution: What Artists Should Compare',
    metaTitle: 'Free vs Paid Music Distribution | FanFactors',
    metaDescription:
      'Compare free and paid distribution through the lens of artist control, data, royalties, support, and long-term fan value.',
    excerpt: 'Free is not always cheap, and paid is not always better. The right choice depends on control and long-term upside.',
    clusterSlug: 'free-music-distribution',
    primaryKeyword: 'free vs paid music distribution',
    secondaryKeywords: ['music distribution fees', 'best distributor for artists', 'artist distribution costs'],
    audience: 'Independent artists',
    searchIntent: 'Compare music distribution options before releasing.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/artist-live-energy.webp',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Distribution cost is only one part of the decision. Artists also need to compare reporting, payout timing, rights terms, and fan data.',
      'The FanFactors view is simple: distribution should not be the only business model. Artists need direct ways to build value with fans.',
    ],
  },
  {
    slug: 'distribution-checklist-for-new-artists',
    title: 'Music Distribution Checklist for New Artists',
    metaTitle: 'Music Distribution Checklist for New Artists | FanFactors',
    metaDescription:
      'Use this checklist before releasing music so your rights, metadata, artwork, fan links, and promotion plan are ready.',
    excerpt: 'A clean release gives every fan action a destination and every song a better chance to build value.',
    clusterSlug: 'free-music-distribution',
    primaryKeyword: 'music distribution checklist',
    secondaryKeywords: ['release checklist', 'new artist distribution', 'music upload checklist'],
    audience: 'Independent artists',
    searchIntent: 'Prepare a release checklist.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '4 min read',
    featuredImage: '/assets/images/funnel-trumpet-player.jpg',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'Before release day, confirm ownership, credits, cover art, release date, links, and the action you want fans to take.',
      'FanFactors turns that final action into more than listening. It points fans toward legal participation in the artist economy.',
    ],
  },
  {
    slug: 'spotify-royalty-calculator-how-much-artists-make',
    title: 'Spotify Royalty Calculator: How Much Artists Make',
    metaTitle: 'Spotify Royalty Calculator: How Much Artists Make | FanFactors',
    metaDescription:
      'Estimate Spotify royalties, understand why payouts vary, and compare streaming income with direct fan-powered value.',
    excerpt:
      'A royalty calculator can estimate stream payouts, but artists also need to understand what the calculator leaves out.',
    clusterSlug: 'spotify-royalties',
    primaryKeyword: 'Spotify royalty calculator',
    secondaryKeywords: ['Spotify royalties', 'streaming payout calculator', 'how much Spotify pays artists'],
    audience: 'Independent artists',
    searchIntent: 'Calculate and understand Spotify royalty estimates.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '7 min read',
    featuredImage: '/assets/images/artist-dj-turntables.webp',
    ctaType: 'artist-alpha',
    status: 'published',
    isPillar: true,
    body: [
      'Spotify royalty estimates are usually based on streams, territory, subscription mix, and rights splits. The final payout can vary widely.',
      'FanFactors asks a bigger question: what if a fan could do more than stream? Direct ownership-style participation can create a different relationship between artists and supporters.',
    ],
  },
  {
    slug: 'why-streaming-royalties-feel-so-small',
    title: 'Why Streaming Royalties Feel So Small',
    metaTitle: 'Why Streaming Royalties Feel So Small | FanFactors',
    metaDescription:
      'Learn why streaming royalties often feel low for independent artists and what other fan-powered revenue paths can add.',
    excerpt: 'Streaming is built for scale, but independent artists often need more than passive plays to survive.',
    clusterSlug: 'spotify-royalties',
    primaryKeyword: 'streaming royalties',
    secondaryKeywords: ['low streaming payouts', 'artist royalties', 'music streaming income'],
    audience: 'Independent artists',
    searchIntent: 'Understand why streaming income is hard to build.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-dj-controller.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Small per-stream payouts can make music feel undervalued, especially when artists fund recording, visuals, touring, and promotion.',
      'FanFactors is designed around direct fan support, artist-set pricing, and legal marketplace mechanics that can sit alongside streaming.',
    ],
  },
  {
    slug: 'spotify-streams-to-income-guide',
    title: 'Spotify Streams to Income: A Practical Guide',
    metaTitle: 'Spotify Streams to Income Guide | FanFactors',
    metaDescription:
      'Convert Spotify stream estimates into practical income expectations and learn why direct fan value can matter more.',
    excerpt: 'Streams can create awareness, but income depends on splits, rights, audience depth, and what fans can do next.',
    clusterSlug: 'spotify-royalties',
    primaryKeyword: 'Spotify streams to income',
    secondaryKeywords: ['Spotify income estimate', 'music streaming money', 'artist revenue'],
    audience: 'Independent artists',
    searchIntent: 'Estimate income from streaming activity.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/artist-pop-collective.webp',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'A stream count is not the same as income. Rights ownership, label splits, distributor fees, and geography all affect payout.',
      'The FanFactors model helps artists think about listeners as potential owners, promoters, and buyers in a legal music marketplace.',
    ],
  },
  {
    slug: 'royalty-calculator-mistakes-artists-make',
    title: 'Royalty Calculator Mistakes Artists Make',
    metaTitle: 'Royalty Calculator Mistakes Artists Make | FanFactors',
    metaDescription:
      'Avoid common royalty calculator mistakes around ownership splits, payout ranges, platform assumptions, and fan value.',
    excerpt: 'Calculators are useful, but they can hide the business assumptions artists need to understand.',
    clusterSlug: 'spotify-royalties',
    primaryKeyword: 'royalty calculator mistakes',
    secondaryKeywords: ['Spotify royalty math', 'artist payout calculator', 'royalty estimate'],
    audience: 'Independent artists',
    searchIntent: 'Avoid mistakes when estimating streaming income.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/artist-extra.webp',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'The biggest mistake is treating an estimate like a promise. Royalty rates move and ownership splits can change the number dramatically.',
      'FanFactors keeps the focus on controllable value: pricing, rights clarity, community demand, and artist-approved transactions.',
    ],
  },
  {
    slug: 'how-to-sell-music-online-direct-to-fans',
    title: 'How to Sell Music Online Direct to Fans',
    metaTitle: 'How to Sell Music Online Direct to Fans | FanFactors',
    metaDescription:
      'Learn how artists can sell music online, build fan demand, and use legal marketplace thinking to create more upside.',
    excerpt: 'Selling music online works best when fans understand what they are buying and why it matters.',
    clusterSlug: 'sell-music-online',
    primaryKeyword: 'sell music online',
    secondaryKeywords: ['sell songs online', 'direct to fan music', 'music sales platform'],
    audience: 'Artists, producers, and small labels',
    searchIntent: 'Find ways to sell music online directly.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '7 min read',
    featuredImage: '/assets/images/artist-hiphop-crew.webp',
    ctaType: 'artist-alpha',
    status: 'published',
    isPillar: true,
    body: [
      'Direct music sales work when the offer is clear: the song, the rights, the price, and the reason fans should care.',
      'FanFactors turns direct sales into a social marketplace where artist-approved music can move with legal clarity.',
    ],
  },
  {
    slug: 'artist-set-pricing-for-music',
    title: 'Artist-Set Pricing for Music: Why It Matters',
    metaTitle: 'Artist-Set Pricing for Music | FanFactors',
    metaDescription:
      'Why artist-set pricing can help musicians test demand, build ownership value, and stop treating every play the same.',
    excerpt: 'When artists set pricing, music can reflect demand, scarcity, community, and cultural value.',
    clusterSlug: 'sell-music-online',
    primaryKeyword: 'artist set pricing',
    secondaryKeywords: ['music pricing', 'sell songs direct', 'artist marketplace'],
    audience: 'Artists, producers, and small labels',
    searchIntent: 'Understand direct music pricing strategy.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/artist-gold-singer.webp',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'Pricing is a signal. It tells fans what the artist believes the work is worth and gives the market a way to respond.',
      'FanFactors supports artist-approved pricing so music can be treated as culture with measurable demand, not just background inventory.',
    ],
  },
  {
    slug: 'sell-songs-without-giving-up-rights',
    title: 'Can Artists Sell Songs Without Giving Up Rights?',
    metaTitle: 'Sell Songs Without Giving Up Rights | FanFactors',
    metaDescription:
      'Learn the difference between selling access, ownership participation, and copyright transfer in a legal music marketplace.',
    excerpt: 'Selling music does not have to mean surrendering everything. The structure and permissions matter.',
    clusterSlug: 'sell-music-online',
    primaryKeyword: 'sell songs without giving up rights',
    secondaryKeywords: ['music rights sales', 'copyright ownership', 'artist rights'],
    audience: 'Artists, producers, and small labels',
    searchIntent: 'Understand rights-safe music sales.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/funnel-blues-guitarist.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Artists should separate copyright ownership, license terms, fan participation, and resale permissions before selling anything.',
      'FanFactors is built around legal clarity so artists can approve how music moves and fans can understand what participation means.',
    ],
  },
  {
    slug: 'direct-to-fan-music-sales-checklist',
    title: 'Direct-to-Fan Music Sales Checklist',
    metaTitle: 'Direct-to-Fan Music Sales Checklist | FanFactors',
    metaDescription:
      'A checklist for artists preparing direct music offers, fan CTAs, pricing, rights language, artwork, and launch messaging.',
    excerpt: 'A direct-to-fan offer needs more than a buy button. It needs trust, clarity, and a reason to act now.',
    clusterSlug: 'sell-music-online',
    primaryKeyword: 'direct to fan music sales',
    secondaryKeywords: ['fan sales checklist', 'sell music direct', 'artist sales funnel'],
    audience: 'Artists, producers, and small labels',
    searchIntent: 'Prepare a direct music sales launch.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '4 min read',
    featuredImage: '/assets/images/funnel-pink-frontwoman-trio.jpg',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'Build the offer around the song, the artist story, the fan benefit, the rights language, the price, and the next action.',
      'FanFactors gives that offer a marketplace home designed for artist control and fan participation.',
    ],
  },
  {
    slug: 'how-to-make-money-as-an-independent-artist',
    title: 'How to Make Money as an Independent Artist',
    metaTitle: 'How to Make Money as an Independent Artist | FanFactors',
    metaDescription:
      'A practical guide to independent artist income from streaming, direct sales, fan support, catalog value, and marketplace thinking.',
    excerpt: 'Independent artists need more than one revenue stream. They need a system that turns fan belief into real demand.',
    clusterSlug: 'make-money-as-independent-artist',
    primaryKeyword: 'how to make money as an independent artist',
    secondaryKeywords: ['independent artist income', 'artist revenue streams', 'music career money'],
    audience: 'Independent artists',
    searchIntent: 'Find ways to make money from music independently.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '8 min read',
    featuredImage: '/assets/images/funnel-rap-vocalist.jpg',
    ctaType: 'artist-alpha',
    status: 'published',
    isPillar: true,
    body: [
      'Independent artist income can come from streaming, shows, merch, sync, licensing, direct sales, subscriptions, and fan-backed campaigns.',
      'FanFactors focuses on the missing layer: a legal social marketplace where artist-approved music can generate direct fan participation.',
    ],
  },
  {
    slug: 'artist-income-beyond-streaming',
    title: 'Artist Income Beyond Streaming',
    metaTitle: 'Artist Income Beyond Streaming | FanFactors',
    metaDescription:
      'Explore music income beyond streaming, including direct fan sales, catalog strategy, promotion, and community value.',
    excerpt: 'Streaming can be part of the mix, but it should not be the only way fans create value for artists.',
    clusterSlug: 'make-money-as-independent-artist',
    primaryKeyword: 'artist income beyond streaming',
    secondaryKeywords: ['music income streams', 'fan support income', 'independent musician money'],
    audience: 'Independent artists',
    searchIntent: 'Compare non-streaming music income options.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/artist-orange-portrait.webp',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Beyond streaming, artists can build income from products, access, fan membership, rights-aware offers, and direct catalog demand.',
      'FanFactors makes the direct path more concrete by connecting music, fans, and marketplace incentives.',
    ],
  },
  {
    slug: 'build-a-fan-economy-around-your-music',
    title: 'Build a Fan Economy Around Your Music',
    metaTitle: 'Build a Fan Economy Around Your Music | FanFactors',
    metaDescription:
      'Learn how independent artists can turn fans into active supporters through pricing, access, participation, and community.',
    excerpt: 'A fan economy starts when listeners have a meaningful role beyond pressing play.',
    clusterSlug: 'make-money-as-independent-artist',
    primaryKeyword: 'fan economy for artists',
    secondaryKeywords: ['music fan community', 'artist fan monetization', 'fan support'],
    audience: 'Independent artists',
    searchIntent: 'Learn how fans can support artists economically.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/artist-bassist-vocalist.webp',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'A fan economy is built from trust, identity, scarcity, proof, and a clear action fans can take.',
      'FanFactors gives that action a legal marketplace structure so fan energy can become measurable artist demand.',
    ],
  },
  {
    slug: 'independent-artist-business-model',
    title: 'The Independent Artist Business Model',
    metaTitle: 'Independent Artist Business Model | FanFactors',
    metaDescription:
      'A simple framework for independent artists building a business around music, fans, catalog, and direct sales.',
    excerpt: 'A music career is a business model. Artists need a way to connect attention, ownership, pricing, and fan trust.',
    clusterSlug: 'make-money-as-independent-artist',
    primaryKeyword: 'independent artist business model',
    secondaryKeywords: ['music business model', 'artist strategy', 'independent music career'],
    audience: 'Independent artists',
    searchIntent: 'Build a practical artist business model.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '7 min read',
    featuredImage: '/assets/images/funnel-afro-bassist.jpg',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'A strong artist model connects audience growth, direct offers, repeat engagement, rights clarity, and long-term catalog value.',
      'FanFactors is built to support that model by making fans part of the market, not just the metrics.',
    ],
  },
  {
    slug: 'make-money-promoting-music-legally',
    title: 'Make Money Promoting Music Legally',
    metaTitle: 'Make Money Promoting Music Legally | FanFactors',
    metaDescription:
      'Learn how fan-powered music promotion could work when incentives, artist approval, and legal rights are handled clearly.',
    excerpt: 'Fans already promote music. The next step is making that energy transparent, legal, and aligned with artists.',
    clusterSlug: 'fan-powered-promotion',
    primaryKeyword: 'make money promoting music',
    secondaryKeywords: ['fan promotion', 'music promotion rewards', 'promote artists legally'],
    audience: 'Fans and artists',
    searchIntent: 'Understand legal ways fans might earn from promoting music.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/funnel-green-mohawk-band.jpg',
    ctaType: 'fan-alpha',
    status: 'published',
    isPillar: true,
    body: [
      'Fans create value every time they introduce music to someone new. The challenge is making that value measurable and legally clean.',
      'FanFactors is designed around artist-approved participation, so fan promotion can support the people who own the music.',
    ],
  },
  {
    slug: 'fan-promotion-vs-playlist-promotion',
    title: 'Fan Promotion vs Playlist Promotion',
    metaTitle: 'Fan Promotion vs Playlist Promotion | FanFactors',
    metaDescription:
      'Compare fan-powered promotion and playlist promotion through trust, incentives, transparency, and artist control.',
    excerpt: 'Playlist promotion can create exposure, but fan promotion can create belief, context, and repeat demand.',
    clusterSlug: 'fan-powered-promotion',
    primaryKeyword: 'fan promotion',
    secondaryKeywords: ['playlist promotion', 'music marketing', 'artist promotion'],
    audience: 'Fans and artists',
    searchIntent: 'Compare music promotion channels.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-metal-band.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Playlist promotion often optimizes for placement. Fan promotion optimizes for human trust and repeated sharing.',
      'FanFactors aims to make fan-powered promotion trackable without separating it from artist approval and rights clarity.',
    ],
  },
  {
    slug: 'how-fans-can-help-break-artists',
    title: 'How Fans Can Help Break Artists',
    metaTitle: 'How Fans Can Help Break Artists | FanFactors',
    metaDescription:
      'Fans can help artists grow by sharing, buying, educating, organizing, and participating in legal marketplace demand.',
    excerpt: 'The most valuable fan is not passive. They help the artist reach the next circle of believers.',
    clusterSlug: 'fan-powered-promotion',
    primaryKeyword: 'fans help artists',
    secondaryKeywords: ['break new artists', 'music fan community', 'artist growth'],
    audience: 'Fans and artists',
    searchIntent: 'Learn how fans can support artist growth.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/artist-magenta-singer.webp',
    ctaType: 'fan-alpha',
    status: 'published',
    body: [
      'Fans help artists break by creating context: why the song matters, who should hear it, and why now.',
      'FanFactors gives fans a clearer role in the music economy while keeping the artist at the center of the permission structure.',
    ],
  },
  {
    slug: 'artist-approved-promotion',
    title: 'Artist-Approved Promotion: The Safer Path',
    metaTitle: 'Artist-Approved Promotion | FanFactors',
    metaDescription:
      'Why music promotion should be artist-approved, rights-aware, and transparent before fans or promoters are rewarded.',
    excerpt: 'Promotion should help artists, not create confusion around rights, attribution, or incentives.',
    clusterSlug: 'fan-powered-promotion',
    primaryKeyword: 'artist approved promotion',
    secondaryKeywords: ['legal music promotion', 'fan rewards', 'music marketing rights'],
    audience: 'Fans and artists',
    searchIntent: 'Understand rights-safe promotion models.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '4 min read',
    featuredImage: '/assets/images/funnel-rainbow-vocalist.jpg',
    ctaType: 'fan-alpha',
    status: 'published',
    body: [
      'Artist-approved promotion protects the people who made the music and gives fans a cleaner way to participate.',
      'FanFactors is built on that principle: promotion, sales, and possible resale should stay tied to permission.',
    ],
  },
  {
    slug: 'music-royalties-explained-for-artists',
    title: 'Music Royalties Explained for Artists',
    metaTitle: 'Music Royalties Explained for Artists | FanFactors',
    metaDescription:
      'A clear guide to music royalties, rights holders, master rights, publishing, performance royalties, and payout paths.',
    excerpt: 'Royalties are easier to understand when artists separate the song, the recording, the usage, and the owner.',
    clusterSlug: 'music-royalties',
    primaryKeyword: 'music royalties explained',
    secondaryKeywords: ['music royalty types', 'master royalties', 'publishing royalties'],
    audience: 'Artists, producers, and music business learners',
    searchIntent: 'Understand music royalty basics.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '8 min read',
    featuredImage: '/assets/images/artist-classic-guitar.webp',
    ctaType: 'learn-more',
    status: 'published',
    isPillar: true,
    body: [
      'Music royalties usually connect to either the composition, the recording, or a specific usage such as performance, mechanical reproduction, or synchronization.',
      'FanFactors keeps royalty education connected to legal marketplace design because rights must be clear before music can be bought, sold, or potentially resold.',
    ],
  },
  {
    slug: 'master-rights-vs-publishing-rights',
    title: 'Master Rights vs Publishing Rights',
    metaTitle: 'Master Rights vs Publishing Rights | FanFactors',
    metaDescription:
      'Learn the difference between master rights and publishing rights before selling, licensing, or promoting music.',
    excerpt: 'The recording and the composition are different assets, and artists need to know which one is being used.',
    clusterSlug: 'music-royalties',
    primaryKeyword: 'master rights vs publishing rights',
    secondaryKeywords: ['music rights explained', 'song ownership', 'recording rights'],
    audience: 'Artists, producers, and music business learners',
    searchIntent: 'Compare major music rights categories.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/funnel-blues-guitarist.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Master rights control the recording. Publishing rights control the underlying song. A single track can involve both.',
      'FanFactors uses rights-aware language because a marketplace cannot be trusted if buyers and fans do not know what is actually being offered.',
    ],
  },
  {
    slug: 'mechanical-performance-sync-royalties',
    title: 'Mechanical, Performance, and Sync Royalties',
    metaTitle: 'Mechanical, Performance, and Sync Royalties | FanFactors',
    metaDescription:
      'Understand the difference between mechanical royalties, performance royalties, and sync royalties in music.',
    excerpt: 'Different uses create different royalties. Artists should know which income stream applies to each opportunity.',
    clusterSlug: 'music-royalties',
    primaryKeyword: 'types of music royalties',
    secondaryKeywords: ['mechanical royalties', 'performance royalties', 'sync royalties'],
    audience: 'Artists, producers, and music business learners',
    searchIntent: 'Learn royalty types.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-horned-rebel.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Mechanical, performance, and sync royalties are tied to different forms of music usage and different collection paths.',
      'A FanFactors marketplace has to respect those distinctions so artist-approved transactions do not blur rights that should stay clear.',
    ],
  },
  {
    slug: 'royalty-splits-for-independent-artists',
    title: 'Royalty Splits for Independent Artists',
    metaTitle: 'Royalty Splits for Independent Artists | FanFactors',
    metaDescription:
      'A practical guide to royalty splits for bands, producers, featured artists, songwriters, and collaborators.',
    excerpt: 'Royalty splits should be discussed before the release, not after the song starts moving.',
    clusterSlug: 'music-royalties',
    primaryKeyword: 'royalty splits',
    secondaryKeywords: ['artist splits', 'producer splits', 'songwriter splits'],
    audience: 'Artists, producers, and music business learners',
    searchIntent: 'Understand how music royalty splits work.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-drummer.jpg',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'Clear splits reduce conflict. Bands, producers, writers, and featured artists should document ownership before distribution.',
      'FanFactors depends on clean rights data because legal fan participation starts with knowing who owns what.',
    ],
  },
  {
    slug: 'best-music-distribution-platforms-for-independent-artists',
    title: 'Best Music Distribution Platforms for Independent Artists',
    metaTitle: 'Best Music Distribution Platforms for Independent Artists | FanFactors',
    metaDescription:
      'Compare music distribution platforms by cost, royalties, support, analytics, control, and direct fan value.',
    excerpt: 'The best distribution platform depends on what an artist needs after the music reaches stores.',
    clusterSlug: 'music-distribution-platforms',
    primaryKeyword: 'best music distribution platforms',
    secondaryKeywords: ['music distributors', 'artist distribution platforms', 'digital music distribution'],
    audience: 'Artists comparing music platforms',
    searchIntent: 'Compare music distribution platforms.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '7 min read',
    featuredImage: '/assets/images/artist-live-energy.webp',
    ctaType: 'artist-alpha',
    status: 'published',
    isPillar: true,
    body: [
      'Distribution platforms can solve delivery, but artists still need to evaluate analytics, rights terms, support, and fan relationship tools.',
      'FanFactors sits beside that decision as a marketplace idea: what can fans do after they discover the music?',
    ],
  },
  {
    slug: 'music-distribution-platform-comparison',
    title: 'Music Distribution Platform Comparison',
    metaTitle: 'Music Distribution Platform Comparison | FanFactors',
    metaDescription:
      'A comparison framework for evaluating music distribution platforms before choosing where to release your songs.',
    excerpt: 'Compare platforms by how they support the artist business, not just where they deliver tracks.',
    clusterSlug: 'music-distribution-platforms',
    primaryKeyword: 'music distribution platform comparison',
    secondaryKeywords: ['compare music distributors', 'music platform fees', 'artist platform comparison'],
    audience: 'Artists comparing music platforms',
    searchIntent: 'Compare distribution platform features.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/artist-pop-collective.webp',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'A good comparison includes delivery, pricing, royalty handling, customer support, analytics, takedown control, and catalog flexibility.',
      'FanFactors adds a separate question: how will the platform help music become valuable to fans beyond streaming?',
    ],
  },
  {
    slug: 'distribution-platforms-vs-marketplaces',
    title: 'Distribution Platforms vs Music Marketplaces',
    metaTitle: 'Distribution Platforms vs Music Marketplaces | FanFactors',
    metaDescription:
      'Learn the difference between platforms that distribute music and marketplaces that let artists and fans transact.',
    excerpt: 'Distribution sends music outward. A marketplace creates a place where demand can gather and move.',
    clusterSlug: 'music-distribution-platforms',
    primaryKeyword: 'music distribution vs marketplace',
    secondaryKeywords: ['music marketplace', 'distribution platform', 'direct fan platform'],
    audience: 'Artists comparing music platforms',
    searchIntent: 'Understand platform categories.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-dj-controller.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Distribution platforms focus on availability. Marketplaces focus on transactions, pricing, and exchange.',
      'FanFactors is the marketplace side of the equation: legal artist-approved music activity between artists and fans.',
    ],
  },
  {
    slug: 'questions-before-choosing-a-music-distributor',
    title: 'Questions Before Choosing a Music Distributor',
    metaTitle: 'Questions Before Choosing a Music Distributor | FanFactors',
    metaDescription:
      'Ask these questions about rights, payout timing, fees, takedowns, analytics, and fan value before choosing a distributor.',
    excerpt: 'The right distributor should fit the business model you want, not just the release date you need.',
    clusterSlug: 'music-distribution-platforms',
    primaryKeyword: 'choosing a music distributor',
    secondaryKeywords: ['music distributor questions', 'artist release platform', 'distribution checklist'],
    audience: 'Artists comparing music platforms',
    searchIntent: 'Evaluate distributor options.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '4 min read',
    featuredImage: '/assets/images/artist-harpist.webp',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'Ask who controls takedowns, who owns the account data, when royalties pay, what fees apply, and how flexible the catalog remains.',
      'Then ask the FanFactors question: how will fans participate when they believe in the music?',
    ],
  },
  {
    slug: 'what-is-a-music-marketplace',
    title: 'What Is a Music Marketplace?',
    metaTitle: 'What Is a Music Marketplace? | FanFactors',
    metaDescription:
      'Learn what a music marketplace is, how it differs from streaming, and why artist-approved fan transactions matter.',
    excerpt: 'A music marketplace is where music can be discovered, valued, bought, supported, and potentially resold legally.',
    clusterSlug: 'music-marketplace',
    primaryKeyword: 'music marketplace',
    secondaryKeywords: ['music rights marketplace', 'fan marketplace', 'music-tech marketplace'],
    audience: 'Artists, fans, investors, and music-tech readers',
    searchIntent: 'Understand music marketplace models.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '7 min read',
    featuredImage: '/assets/images/funnel-dj-controller.jpg',
    ctaType: 'learn-more',
    status: 'published',
    isPillar: true,
    body: [
      'A music marketplace is different from a streaming service. It gives artists and fans a place to transact, support, and signal demand.',
      'FanFactors is building that idea around legal rights, artist-approved terms, and social fan participation.',
    ],
  },
  {
    slug: 'social-music-marketplace',
    title: 'What Makes a Music Marketplace Social?',
    metaTitle: 'Social Music Marketplace | FanFactors',
    metaDescription:
      'A social music marketplace connects discovery, fan identity, artist support, and legal transactions in one ecosystem.',
    excerpt: 'Music spreads socially. A marketplace should let that social energy create value for artists and fans.',
    clusterSlug: 'music-marketplace',
    primaryKeyword: 'social music marketplace',
    secondaryKeywords: ['music social platform', 'fan marketplace', 'music community'],
    audience: 'Artists, fans, investors, and music-tech readers',
    searchIntent: 'Understand social marketplace mechanics.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/artist-hiphop-crew.webp',
    ctaType: 'fan-alpha',
    status: 'published',
    body: [
      'A social marketplace does not separate discovery from action. The fan who finds the song can also support and share it.',
      'FanFactors brings that loop into a rights-aware music marketplace.',
    ],
  },
  {
    slug: 'music-marketplace-for-artists-and-fans',
    title: 'A Music Marketplace for Artists and Fans',
    metaTitle: 'Music Marketplace for Artists and Fans | FanFactors',
    metaDescription:
      'Why a better music marketplace has to serve artists, fans, rights owners, and the culture around songs.',
    excerpt: 'Artists need control. Fans need a meaningful role. A music marketplace should be designed for both.',
    clusterSlug: 'music-marketplace',
    primaryKeyword: 'music marketplace for artists',
    secondaryKeywords: ['artist marketplace', 'fan marketplace', 'music ownership platform'],
    audience: 'Artists, fans, investors, and music-tech readers',
    searchIntent: 'Evaluate who benefits from a music marketplace.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/funnel-afro-bassist.jpg',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'A marketplace only works if artists trust it, fans understand it, and rights are respected.',
      'FanFactors is shaped around those requirements because music culture needs a better economic layer.',
    ],
  },
  {
    slug: 'legal-music-marketplace-principles',
    title: 'Legal Music Marketplace Principles',
    metaTitle: 'Legal Music Marketplace Principles | FanFactors',
    metaDescription:
      'The principles a legal music marketplace needs: rights clarity, artist approval, transparent terms, and fan trust.',
    excerpt: 'A music marketplace without rights clarity is not a revolution. It is a liability.',
    clusterSlug: 'music-marketplace',
    primaryKeyword: 'legal music marketplace',
    secondaryKeywords: ['music rights marketplace', 'artist approved marketplace', 'fan trust'],
    audience: 'Artists, fans, investors, and music-tech readers',
    searchIntent: 'Learn requirements for legal music marketplaces.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-metal-vocalist-band.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Legal marketplaces need clear rights, clear offers, clear records, and clear limits on what fans can do.',
      'FanFactors treats legal design as a feature because trust is the foundation of any future music resale system.',
    ],
  },
  {
    slug: 'music-resale-rights-explained',
    title: 'Music Resale Rights Explained',
    metaTitle: 'Music Resale Rights Explained | FanFactors',
    metaDescription:
      'Learn what music resale rights could mean, why legal permission matters, and how artists and fans may benefit.',
    excerpt: 'Music resale rights only make sense when the artist, rights owner, and fan all understand the rules.',
    clusterSlug: 'music-resale-rights',
    primaryKeyword: 'music resale rights',
    secondaryKeywords: ['resell music rights', 'music ownership resale', 'fan music rights'],
    audience: 'Artists, fans, and future FanFactors users',
    searchIntent: 'Understand music resale rights.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '7 min read',
    featuredImage: '/assets/images/funnel-metal-vocalist-band.jpg',
    ctaType: 'learn-more',
    status: 'published',
    isPillar: true,
    body: [
      'Music resale rights are not a shortcut around copyright. They require permission, terms, records, and a marketplace that respects ownership.',
      'FanFactors is exploring resale as a legal artist-approved feature, not a free-for-all.',
    ],
  },
  {
    slug: 'can-fans-resell-music-legally',
    title: 'Can Fans Resell Music Legally?',
    metaTitle: 'Can Fans Resell Music Legally? | FanFactors',
    metaDescription:
      'A plain-language look at when fans can and cannot resell music, and why artist-approved rights matter.',
    excerpt: 'Fans should not guess about resale. Legal resale depends on what rights were actually granted.',
    clusterSlug: 'music-resale-rights',
    primaryKeyword: 'can fans resell music legally',
    secondaryKeywords: ['legal music resale', 'fan resale rights', 'music rights'],
    audience: 'Artists, fans, and future FanFactors users',
    searchIntent: 'Understand legal boundaries for fan resale.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/artist-mohawk-rebel.jpg',
    ctaType: 'fan-alpha',
    status: 'published',
    body: [
      'Whether a fan can resell depends on the terms attached to what they bought. Access, ownership, and license rights are different.',
      'FanFactors is designed to make those terms visible before any marketplace action happens.',
    ],
  },
  {
    slug: 'artist-approved-resale',
    title: 'Artist-Approved Resale: Why Permission Matters',
    metaTitle: 'Artist-Approved Resale | FanFactors',
    metaDescription:
      'Why any future music resale system should start with artist approval, rights clarity, and transparent market rules.',
    excerpt: 'Resale should create new upside for music culture, not new confusion for artists.',
    clusterSlug: 'music-resale-rights',
    primaryKeyword: 'artist approved resale',
    secondaryKeywords: ['music resale marketplace', 'artist rights', 'fan resale'],
    audience: 'Artists, fans, and future FanFactors users',
    searchIntent: 'Learn why permission matters in music resale.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-horned-rebel.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'Permission protects the artist and gives fans confidence that marketplace activity is legitimate.',
      'FanFactors makes artist approval central because resale without trust cannot become a durable music economy.',
    ],
  },
  {
    slug: 'future-of-music-ownership',
    title: 'The Future of Music Ownership',
    metaTitle: 'The Future of Music Ownership | FanFactors',
    metaDescription:
      'How music ownership could evolve through legal marketplaces, artist-approved participation, and fan-powered demand.',
    excerpt: 'Music ownership needs a future that respects copyright and gives fans a deeper role in culture.',
    clusterSlug: 'music-resale-rights',
    primaryKeyword: 'future of music ownership',
    secondaryKeywords: ['music ownership', 'music rights marketplace', 'fan ownership'],
    audience: 'Artists, fans, and future FanFactors users',
    searchIntent: 'Explore future music ownership models.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/artist-glam-portrait.webp',
    ctaType: 'fan-alpha',
    status: 'published',
    body: [
      'The future of music ownership must be understandable, legal, and artist-approved.',
      'FanFactors is working toward a social marketplace where fans can help music move while artists keep control of the rules.',
    ],
  },
  {
    slug: 'what-is-fanfactors-taking-music-back',
    title: "What Is FanFactors? We're Taking Music Back™",
    metaTitle: "What Is FanFactors? We're Taking Music Back™",
    metaDescription:
      'FanFactors is a social music marketplace where artists can upload music and fans can buy, sell, and potentially resell music rights legally.',
    excerpt:
      "FanFactors is built around one idea: music should create more value for the artists and fans who make culture move.",
    clusterSlug: 'fanfactors-revolution',
    primaryKeyword: 'FanFactors',
    secondaryKeywords: ['music marketplace', 'taking music back', 'artist fan marketplace'],
    audience: 'Artists, fans, early adopters, and supporters',
    searchIntent: 'Learn what FanFactors is.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '6 min read',
    featuredImage: '/assets/images/artist-mohawk-rebel.jpg',
    ctaType: 'learn-more',
    status: 'published',
    isPillar: true,
    body: [
      "FanFactors is a social music marketplace for artists and fans. Artists upload music. Fans can discover, buy, support, and potentially resell artist-approved music rights legally inside the platform.",
      "We're taking music back™ means rebuilding music around ownership, direct support, and fan-powered demand instead of passive consumption alone.",
    ],
  },
  {
    slug: 'why-fanfactors-exists',
    title: 'Why FanFactors Exists',
    metaTitle: 'Why FanFactors Exists | FanFactors',
    metaDescription:
      'FanFactors exists because artists need more control, fans need a real role, and music needs a better marketplace.',
    excerpt: 'The current music economy creates attention without enough ownership. FanFactors is building a different path.',
    clusterSlug: 'fanfactors-revolution',
    primaryKeyword: 'why FanFactors exists',
    secondaryKeywords: ['music revolution', 'artist ownership', 'fan economy'],
    audience: 'Artists, fans, early adopters, and supporters',
    searchIntent: 'Understand the FanFactors mission.',
    funnelStage: 'awareness',
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/funnel-metal-band.jpg',
    ctaType: 'learn-more',
    status: 'published',
    body: [
      'FanFactors exists because music culture deserves a business model where artists and fans can both participate more directly.',
      'The mission is not to abandon streaming. It is to add a legal marketplace layer that gives music more ways to create value.',
    ],
  },
  {
    slug: 'artists-and-fans-own-the-movement',
    title: 'Artists and Fans Own the Movement',
    metaTitle: 'Artists and Fans Own the Movement | FanFactors',
    metaDescription:
      'How FanFactors frames artists and fans as the center of a new legal music marketplace movement.',
    excerpt: 'A movement only matters if the people who make and support the music have a real role in it.',
    clusterSlug: 'fanfactors-revolution',
    primaryKeyword: 'artists and fans',
    secondaryKeywords: ['music movement', 'fan ownership', 'artist control'],
    audience: 'Artists, fans, early adopters, and supporters',
    searchIntent: 'Learn how artists and fans fit into FanFactors.',
    funnelStage: 'consideration',
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '5 min read',
    featuredImage: '/assets/images/artist-magenta-singer.webp',
    ctaType: 'fan-alpha',
    status: 'published',
    body: [
      'Artists bring the music. Fans bring belief, attention, and distribution energy. FanFactors is designed to connect those roles.',
      "We're taking music back™ is a market message and a cultural one.",
    ],
  },
  {
    slug: 'join-the-fanfactors-alpha',
    title: 'Join the FanFactors Alpha',
    metaTitle: 'Join the FanFactors Alpha | FanFactors',
    metaDescription:
      'Learn why early artists, fans, and supporters should join the FanFactors Alpha and help shape the music marketplace.',
    excerpt: 'The alpha is where early believers help shape how the FanFactors marketplace should work.',
    clusterSlug: 'fanfactors-revolution',
    primaryKeyword: 'FanFactors Alpha',
    secondaryKeywords: ['join FanFactors', 'music marketplace alpha', 'early access'],
    audience: 'Artists, fans, early adopters, and supporters',
    searchIntent: 'Join or learn about FanFactors early access.',
    funnelStage: 'conversion',
    publishedAt: '2026-05-10',
    updatedAt: '2026-05-13',
    author: 'FanFactors',
    readingTime: '4 min read',
    featuredImage: '/assets/images/fanfactors-wordmark-dark.png',
    ctaType: 'artist-alpha',
    status: 'published',
    body: [
      'The FanFactors Alpha is for artists, fans, and supporters who believe music needs a better business layer.',
      'Early feedback helps shape the marketplace before it scales.',
    ],
  },
]
